Gosi/urls.py
from django.urls import path
from .views import main,main2,main3,create

app_name = "Gosi"

urlpatterns = [
    path('', main, name = "main"),
    path('input/',main3, name ="input"),
    path('create/',create, name ="create"),
]

Honbab/urls.py
from django.urls import path
from .views import resturant_like,index
from django.conf.urls import url

app_name = "Honbab"
urlpatterns = [
    url(r'^$', index, name='main'),
    url(r'^(?P<pk>\d+)/like/$', resturant_like, name='resturant_like'), 
]

Menu/urls.py
from django.contrib import admin
from django.urls import path, include
from Gosi.views import main , main2, main3 ,create
from Honbab.views import Honbab
import accounts.views




urlpatterns = [
    path('admin/', admin.site.urls),
    path('gosi/', include('Gosi.urls')),
    path('honbab/', include('Honbab.urls')),
    path('',main2 , name = "main"),
    path('accounts/',include('accounts.urls'))
]

Gosi/models.py
from django.db import models
from datetime import datetime
from django.utils.dateformat import DateFormat
from datetime import timedelta
import datetime

# Create your models here.


class Gosi(models.Model):
    Gosiname = models.CharField(max_length=200)

    morning = models.TextField()    
    lunch = models.TextField()    
    dinner = models.TextField()    
    
    date = models.DateField()
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

Gosi/views.py
from datetime import datetime
from django.utils.dateformat import DateFormat
from django.shortcuts import render,redirect
from .models import Gosi
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required

def main(request):
    context = {
         'Gosis' : Gosi.objects.all(),
         'Pyear' : datetime.today().year,
         'Pmonth' : datetime.today().month,
         'Pday' : datetime.today().day,

    }
    return render(request,'Gosi/gosis.html', context)

def main2(request):
    return render(request,'Gosi/main.html')

@staff_member_required
def main3(request):
    return render(request,'Gosi/input.html')

def create(request):
    if request.method == "POST":
        Gosiname = request.POST.get('Gosiname')
        
        morning = request.POST.get('morning')
        lunch = request.POST.get('lunch')
        dinner = request.POST.get('dinner')
        
        date = request.POST.get('date')
        
        Gosi.objects.create(Gosiname = Gosiname, morning = morning, lunch = lunch, dinner = dinner, date = date)
        
        return redirect('main')

Gosi/templates/Gosi/gosis.html
{% include 'share/navbar.html' %}
<html lang="en">
<head>
  <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
	<link href="https://fonts.googleapis.com/css?family=Nanum+Myeongjo|Single+Day|Yeon+Sung&display=swap" rel="stylesheet">
    <style>
	.card-header{font-family: 'Nanum Myeongjo', serif; font-size : 20pt;}
	
      p { margin:40px 0px; }
	  table {
    
    border-top: 1px solid #444444;
    border-collapse: collapse;
  }
  th, td {
    border-bottom: 1px solid #444444;
    text-align: center;
  }
  thead tr {
  
    background-color: #0d47a1;
    color: #ffffff;
  }
  tbody tr:nth-child(2n) {
    font-size : 11pt;
    font-family: 'Single Day', cursive;
    background-color: #f6f6f6;
  }
  tbody tr:nth-child(2n+1) {
  font-family: 'Yeon Sung', cursive;
  font-size : 18pt;
   color: #f6f6f6;
    background-color: #8785a2;
  }
    </style>
      


    <title>고시식당 오늘의 메뉴</title>
  </head>
             
    
  <body>
   <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

      
<div class="container"> 
  <div class="row">
 
{% for i in Gosis %}
   {% if i.date.year == Pyear %}
   {% if i.date.month == Pmonth %}
   {% if i.date.day == Pday %}
        <div class="col-6">
          <div class="card">
            <div class="card-header" align = "center">
              식당 : {{i.Gosiname}} <br> {{i.date}}
            </div>
            <img src="images/card-image.png" alt="" />
            <div class="card-body" >
              <table border="3" bordercolor="gray" width ="300" height="500" align = "center" >
    
	
	<tr align = "center" height = "30"><!-- 첫번째 줄 시작 -->
	    <td>아침
	
	<tr align = "center" font = "red"><!-- 첫번째 줄 시작 -->		
		<td>{{i.morning}}
		
	<tr align = "center" height = "30"><!-- 첫번째 줄 시작 -->
	    <td>점심
	
	<tr align = "center" ><!-- 첫번째 줄 시작 -->		
		<td>{{i.lunch}} 	
		
	<tr align = "center" height = "30"><!-- 첫번째 줄 시작 -->
	    <td>저녁
	
	<tr align = "center" ><!-- 첫번째 줄 시작 -->		
		<td>{{i.lunch}}  
	    
	</tr><!-- 세번째 줄 끝 -->
    </table>
            </div>
          </div>
        </div>

    {% endif %}
    {% endif %}
    {% endif %}
	
{% endfor %}
  
      

  </div>
</div>

   
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
                
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
  
                
    </body>
</html>

Gosi/templates/Gosi/input.html
{% extends 'base.html' %}

{% block content %}
{% include 'share/navbar.html' %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" >
<link rel="stylesheet" href="resources/css/plugin/datepicker/bootstrap-datepicker.css">

<script src="https://code.jquery.com/jquery-3.2.1.js"></script>
<script src="resources/js/plugin/datepicker/bootstrap-datepicker.js"></script>


<!--한국어  달력 쓰려면 추가 로드-->
<script src="resources/js/plugin/datepicker/bootstrap-datepicker.ko.min.js"></script>
		<script src="http://code.jquery.com/jquery-1.10.2.js"></script>
		<script src="http://code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
	
		<link rel="stylesheet" href="http://code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
	
		<script>
			$(function() {
				$( ".Datepicker" ).datepicker( {
					dateFormat:"YYYY-MM-DD"
				});
			});
		</script>



<div class="container">

<form action ="{% url 'Gosi:create' %}" method = "POST">
    {% csrf_token %}
      
      <div class="form-group">
        <label for="exampleFormControlSelect1">식단 제출</label>
        <select class="form-control" id="exampleFormControlSelect1" name ="Gosiname">
          <option selected> 식당이름 선택하세요</option>
          <option>통통이</option>
          <option>레알짱</option>
          <option>3D고시</option>
          <option>골든볼9</option>
          <option>식객</option>
          <option>밥드림</option>
          <option>패스</option>
          <option>언덕</option>
          <option>애플</option>
          <option>노량진</option>

        </select>
      </div>
        
    <div class = "form-group"> 날짜 선택 해주세요 </div>
      
      <div class="col-md-4 mb-4"> <label for="validationCustom03"></label> 
          <input type="date" class="DatePicker" class="form-control" value="2020-01-01" name = "date">

      <div class="form-group">
        <label for="exampleFormControlTextarea11">아침 메뉴 입력해 주세요 </label>
        <textarea class="form-control" id="exampleFormControlTextarea11" rows="4" name="morning"></textarea>
      </div>
    
       <div class="form-group">
        <label for="exampleFormControlTextarea12">점심 메뉴 입력해 주세요 </label>
        <textarea class="form-control" id="exampleFormControlTextarea12" rows="4" name="lunch"></textarea>
      </div>
    
       <div class="form-group">
        <label for="exampleFormControlTextarea13">저녁 메뉴 입력해 주세요 </label>
        <textarea class="form-control" id="exampleFormControlTextarea13" rows="4" name="dinner"></textarea>
      </div>
    
    <input type="submit" value = "등록" class="btn btn-outline-primary" href="{% url 'Gosi:input' %}"  >
    
</form>
    
</div>
{% endblock %}

Gosi/templates/Gosi/main.html
{% extends 'base.html' %}

{% block content %}
<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width", initial-scale="1">
    <title>혼밥</title>
    <link rel="stylesheet" href="css/bootstrap.css">
</head>
<body>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>



    <style type="text/css">
        .background {
            background : lightyellow;
            background-repeat : no-repeat;
            background-size : cover;
            
        }
        
        .jumbotron {
            background-color: powderblue;
            background-size: cover;
            text-shadow: black 0.15em 0.15em 0.15em;
            box-shadow : black 0.3em 0.3em 0.3em;
            color: white;
            margin-top : 4.5%;
        }
    </style>
    
    
   <div class="background">
       
     
    
   <div class="container">
        <div class="jumbotron"> 
            <h1 class="text-center">고시식당 메뉴를 소개합니다.</h1>
            <p class="text-center">노량진에 있는 고시식당의 메뉴를 한 눈에 정리해 드립니다.</p>
            <p class="text-center"><a class="btn btn-secondary btn-lg" href="{% url 'Gosi:main' %}" role="button">메뉴 보러가기</a></p>
        
            </div>     
    </div>
    
     
    <div class="container">
        <div class="jumbotron">
            <h1 class="text-center">혼밥식당을 소개합니다.</h1>
            <p class="text-center">혼자 밥을 먹을 수 있는 식당의 특징들을 자세히 알려주는 사이트 입니다.</p>
            <p class="text-center"><a class="btn btn-secondary btn-lg" href="{% url 'Honbab:main' %}" role="button">식당 보러가기</a></p>
        </div>
    </div>
   
</div>       
       </body>
</html>
{% endblock %}