Gosi/urls.py
from django.urls import path
from .views import main,main2,main3,create

app_name = "Gosi"

urlpatterns = [
    path('', main, name = "main"),
    path('input/',main3, name ="input"),
    path('create/',create, name ="create"),
]

Honbab/urls.py
from django.urls import path
from .views import resturant_like,index
from django.conf.urls import url

app_name = "Honbab"
urlpatterns = [
    url(r'^$', index, name='main'),
    url(r'^(?P<pk>\d+)/like/$', resturant_like, name='resturant_like'), 
]

Menu/urls.py
from django.contrib import admin
from django.urls import path, include
from Gosi.views import main , main2, main3 ,create
from Honbab.views import Honbab
import accounts.views




urlpatterns = [
    path('admin/', admin.site.urls),
    path('gosi/', include('Gosi.urls')),
    path('honbab/', include('Honbab.urls')),
    path('',main2 , name = "main"),
    path('accounts/',include('accounts.urls'))
]

accounts/urls.py
from django.urls import path
from django.conf.urls import url
from .views import login,logout,signup

app_name = "accounts"
urlpatterns = [
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^signup/$', signup, name='signup'),
]

Menu/templates/share/navbar.html
<ul class="nav navbar-nav">
	{% if user.is_authenticated %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark navbar-left">
        <a class="navbar-brand" href="#">고시&혼밥</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
          
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-item nav-link active" href="/">메인페이지<span class="sr-only">(current)</span></a>

              <a class="nav-item nav-link active" href='{% url "Gosi:main" %}'>고시식당</a>
              <a class="nav-item nav-link active " href='{% url "Honbab:main" %}'>혼밥</a>
              <li><a class="nav-item nav-link active" href="{% url 'accounts:logout' %}">로그아웃</a></li>
            
	    {% else %}
                
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark navbar-left">
          <a class="navbar-brand" href="#">고시&혼밥</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-item nav-link active" href="/">메인페이지<span class="sr-only">(current)</span></a>

                <a class="nav-item nav-link active" href='{% url "Gosi:main" %}'>고시식당</a>
              <a class="nav-item nav-link active" href='{% url "Honbab:main" %}'>혼밥</a>
              <li><a class="nav-item nav-link active" href="{% url 'accounts:login' %}">로그인</a></li>
             <li><a class="nav-item nav-link active" href="{% url 'accounts:signup' %}">회원가입</a></li>
        
	
	{% endif %}
</ul>