Gosi/urls.py
from django.urls import path
from .views import main,main2,main3,create

app_name = "Gosi"

urlpatterns = [
    path('', main, name = "main"),
    path('input/',main3, name ="input"),
    path('create/',create, name ="create"),
]

Honbab/urls.py
from django.urls import path
from .views import resturant_like,index
from django.conf.urls import url

app_name = "Honbab"
urlpatterns = [
    url(r'^$', index, name='main'),
    url(r'^(?P<pk>\d+)/like/$', resturant_like, name='resturant_like'), 
]

Menu/urls.py
from django.contrib import admin
from django.urls import path, include
from Gosi.views import main , main2, main3 ,create
from Honbab.views import Honbab
import accounts.views




urlpatterns = [
    path('admin/', admin.site.urls),
    path('gosi/', include('Gosi.urls')),
    path('honbab/', include('Honbab.urls')),
    path('',main2 , name = "main"),
    path('accounts/',include('accounts.urls'))
]

Honbab/models.py
from django.conf import settings
from django.db import models

# Create your models here.


class Honbab(models.Model):
    
    restraunt = models.CharField(max_length=200)
    
    level = models.CharField(max_length=10) #혼밥레벨
    menu = models.TextField()  # 주메뉴  
    img = models.TextField()   # 식당 이미지
    like_user_set = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                           blank=True,
                                           related_name='like_user_set',
                                           through='Like',
                                           through_fields=('post', 'user'),
                                           )
                                           
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
                                           
    @property                                          
    def like_count(self):
        return self.like_user_set.count()
    
class Like(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    post = models.ForeignKey(Honbab,on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
                                           

Honbab/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.views.decorators.http import require_POST
from .models import Honbab ,Like



@login_required
def resturant_like(request,pk):
    resturant = get_object_or_404(Honbab, pk=pk)
  # 중간자 모델 Like 를 사용하여, 현재 post와 request.user에 해당하는 Like 인스턴스를 가져온다.
    resturant_like, resturant_like_created = resturant.like_set.get_or_create(user=request.user)

    if not resturant_like_created:
        resturant_like.delete()

    return redirect('Honbab:main') 

def index(request):
    sort = request.GET.get('sort','')
    if sort == 'Likes':
        honbab = Honbab.objects.order_by('-like_user_set')
        return render(request, 'Honbab/Honbab.html', {'Honbab' : honbab})
    else:
        honbab = Honbab.objects.order_by('level')
        return render(request, 'Honbab/Honbab.html', {'Honbab' : honbab})

Honbab/templates/Honbab/Honbab.html
{% extends 'base.html' %}

{% block content %}
{% include 'share/navbar.html' %}

<select style="float: right;" id="sort-select" onchange="location = this.value;">
  <option class="sort-Likes" value="?sort=Likes">좋아요순</option>
  <option class="sort-level" value="?sort=level">혼밥레벨순</option>
</select>

<style type="text/css">
        .buttons {
            font color: white;
            padding-top : 30px;
           }
</style>

{% for honbab in Honbab %}
<center>
<div class="card" style= "width:70%; height:17%; margin-bottom:10%; margin-top:10%;">
  <h5 class="card-header" style = "text-align:left;">{{honbab.restraunt}}</h5>
  <div class="card-body">
    <h5 class="card-title" style = "text-align:left;">Lv.{{honbab.level}}</h5>
    <pre class="card-text" style = "text-align:left;">{{honbab.menu}}.</pre>
      <img src= {{honbab.img}} id="imagepreview" style="width: 80%; height : 80%;" alt="...">
    <div class = buttons><a class="btn btn-primary" data-target="#modal" data-toggle="modal">쿠폰 받기</a></div>
<h5 style ="text-align:right;"><li>
         <a href="{% url 'Honbab:resturant_like' honbab.pk %}">{{ honbab.like_user_set.count }} like{{ honbab.like_user_set.count|pluralize }} </a>
         {% for like_user in post.like_user_set.all %}
         {{ like_user.profile.nickname }}
         {% endfor %} 
      </li>  </h5>
    
</div>
</div>
    </center>
    
    
     <div class="row">
        <div class= "modal" id="modal" tabindex="-1">
            <div class= "modal-dialog">
                <div class= "modal-content">
                    <div class= "modal-header">
                        <h5 class="modal title" id="modallabel">쿠폰 받기</h5>
                        <button class="close" data-dismiss="modal" aria-label="Close">&times;</button>
                        
                        </div>
                    <div class="modal-body" style="text-align: center;">
 <input type="text" name="Phone Number" class="form-control" placeholder="01012345678">
                        <hr/>
                        <p style = "text-align:left;">휴대폰 번호를 입력하신 후 '쿠폰받기'를 클릭해주세요.</p>
                
                        <span style = font-size:13px;><p style = "text-align:left;">- 쿠폰 내용이 들어갈 자리입니다.</p></span> 
                    </div>
                    <div class="modal-footer">
                        <input type ="submit" class="btn btn-primary" value="쿠폰받기">
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endfor %}

<script>
    
var getUrlParameter = function getUrlParameter(sParam) {
var sPageURL = decodeURIComponent(window.location.search.substring(1)),
    sURLVariables = sPageURL.split('&'),
    sParameterName,
    i;

for (i = 0; i < sURLVariables.length; i++) {
    sParameterName = sURLVariables[i].split('=');

    if (sParameterName[0] === sParam) {
        return sParameterName[1] === undefined ? true : sParameterName[1];
    }
}
};
    
$(document).ready(function(){
  var sort = getUrlParameter('sort');
  if(sort == 'Likes'){
    $('.sort-Likes').prop('selected', 'selected')
  }else{
    $('.sort-level').prop('selected', 'selected')
  }
});
</script>

{% endblock %}